### ISSUE TITLE
Menu scroll

### ISSUE THREAD

**Issue by timersys** [ahmedrad/sliiide#10]
HI, Im trying the script but for example I got a large menu that is around 500pixels height. While this is fine on portait , on landscape the phone height is 375 so I need to scroll the menu in order to see all items but currently is not posible.

Thanks

**Comment by ahmedrad** [comment]
Hi @timersys,

You'll have to not use my built in no_scroll feature, just set it to false when you're initializing sliiide. For example your settings object would look like this.
```
var settings = {
            toggle: "#sliiider-toggle", 
            exit_selector: ".slider-exit",
            animation_duration: "0.5s",
            place: "left",
            animation_curve: "cubic-bezier(0.54, 0.01, 0.57, 1.03)", 
            body_slide: true, 
            no_scroll: fales
                };
```
that way both your website and menu would be able to scroll, if you would still like your main website to not scroll and your menu to scroll then I suggest using a more advanced plugin for controlling disabling the scroll. this is a good plugin to do that https://github.com/ultrapasty/jquery-disablescroll
you can disable scroll on all children of body except the sliiide menu. Personally, after the last update the position of the menu is fixed while scrolling on almost all the browsers I tested so I'd just leave the scrolling enabled on the website and the menu. Hope this helps!

**Comment by timersys** [comment]
That's what I tried first but that doesn't work because the height of the menu its calculated by your script which makes it as height as the window vieport rather content.
I ended modifying the script to achieve what I wanted but it's very specific to my site so I won't send a pull request, but would be a nice feature ot consider.
Thanks!

**Comment by ahmedrad** [comment]
I'm not sure what the feature would be, The plugin stretches the menu to the viewport height if it's coming in from the side or stretches the width if it's coming in from the top or bottom. Making the height of the menu longer than the viewport wouldn't create the best look or experience. I thought you'd just be looking to add a css property to the menu of overflow-y: scroll; .. wouldn't that solve the problem of larger content than the menu height and have users be able to scroll through it?
