### ISSUE TITLE
Stay open

### ISSUE THREAD

**Issue by DeNelo** [ahmedrad/sliiide#12]
Hi,
Is there any way to make the menu stay open after clicking a link?
-Niels

**Comment by jotapee** [comment]
I have the very same issue, is there any update regarding this?

I have tried with <a>, <span>, <button>, everything. When you click on something the menu closes itself. I don't understand what's the point of specifying a class or id on exit_selector if any link will close the menu.

Thanks in advance for any news regarding this.

**Comment by justrealmilk** [comment]
+1

**Comment by justrealmilk** [comment]
`$("a:not(.sliiider-toggle, .slider-exit)").off('click');`

Thought of a solution that doesn't require editing the library. I placed it after the slider init code.

**Comment by justrealmilk** [comment]
No idea how to GitHub, but I forked this repo and fixed it myself. :-)

**Comment by ahmedrad** [comment]
It should just be the line mentioned by @justrealmilk ```$sliiider.find('a').on('click', function() {deactivate();});```

I dunno why when you use span or button tags it still closes, can you send me an example @jotapee ?

It's a good point though I should make it an option instead.

**Comment by jotapee** [comment]
HI @ahmedrad I can create a fiddle for you, np, but its super easy to recreate. Simply include any link within the sliiide panel and it will close when you click on it. Also happens with span and button. 
Thanks @justrealmilk for you help, I will try your script to see how it goes.
Best!

**Comment by ahmedrad** [comment]
the latest release now has an auto_close option @jotapee @DeNelo @justrealmilk .. sorry for the delay. Closing this issue
