### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by DeNelo** [ahmedrad/sliiide#13]
I use sliiide. My site is rather large, with 450+ links in the sliiide pane. As a result, there's a white flash every time I load a page on the site because the sliiide panel is loaded.
Does anyone have any ideas to:
- Cache the pane and read it from a file or memory
- Defer the loading of the sliiide pane until everything else has loaded
- Or something else?

That would be really helpful. Doesn't somebody else have this problem?

**Comment by ahmedrad** [comment]
I'm sorry @DeNelo I don't think it's common to have 450+ links in a pane, are your website users expected to read through all of them? maybe if you send me a link to the website I can troubleshoot a little but I won't be able to optimize it for this large of a website as it's just not a common case

**Comment by DeNelo** [comment]
It's OK @ahmedrad. Maybe I can find a developer here to take a look, and maybe it's just not very relevant. My users use the pane to see where they are in the total book. And no, it's more like a reference... and it's on the inside of a firewall so you can't even get to see it unfortunately.
