### ISSUE TITLE
License info

### ISSUE THREAD

**Issue by clairetsai818** [ahmedrad/sliiide#16]
Hi! I am a member of [CDNJS](https://github.com/cdnjs/cdnjs)!
We would like to add this library to our CDN, and we need to check if its license is MIT. Thanks!
[issue ref](https://github.com/cdnjs/cdnjs/issues/10112)

**Comment by ahmedrad** [comment]
Hi @clairetsai818 so sorry I'll fix up the license.

Also so sorry for the late reply.

**Comment by ahmedrad** [comment]
Done @clairetsai818
