### ISSUE TITLE
shadow should also be able to handle toggle 

### ISSUE THREAD

**Issue by a8568730** [ahmedrad/sliiide#3]
When shadow pop up, click shadow should also deactivate sliiide too.

**Comment by generatepress** [comment]
I did this by adding an empty element to my HTML:

    <div class="slideout-overlay" style="display: none;"></div>

Then adding this javascript:

    jQuery( document ).on( 'click', '.slideout-toggle', function( event ) {
        event.preventDefault();
        menu.activate();
        jQuery( '.slideout-overlay' ).show();
    });

    jQuery( document ).on( 'click', '.slideout-overlay', function( event ) {
        event.preventDefault();
        menu.deactivate();
        jQuery( '.slideout-overlay' ).hide();
    });

**Comment by ahmedrad** [comment]
I tried to do this with CSS styling but couldn't get it to work, I'm really hoping to avoid editing the DOM tree with this plugin this is why I'm avoiding adding any overlays but glad the branch is here in case anyone is looking for this feature specifically. Thanks for the contribution @a8568730 @generatepress
