### ISSUE TITLE
Toggle image by click or swipe

### ISSUE THREAD

**Issue by lauralisa** [ahmedrad/sliiide#5]
Hi,

I create a panel menu with Sliiide. I want to toggle the menu image when opening and closing the menu, by click or when swiping. How can I do this? Click is working, but not when swiping.
Example: lauralisa.nl/ralf (user rm/pass 643).

TIA!
Regards, Laura

**Comment by ahmedrad** [comment]
Hi Laura,

The plugin is not built with a swipe functionality but you do have access to the activate() and deactivate() functions that is in the returned object after activating sliiide. If you want it to work with a swipe event just make an event listener that calls the activate() function.

the code would look something like this

```
<button id="nav-open">open menu</button>
<div id="my-menu"><a>link1</a><a>linke2</a><a class="close-link">Close</a></div>
<script>
var menu = $('#my-menu').sliiide({place: 'left', exit_selector: '.close-link', toggle: '#nav-open', no_scroll: true});

$(window).on('swiperight', function() {menu.activate();});
$(window).on('swipeleft', function(){menu.deactivate();});
</script>
```

Hope this helps! :)

**Comment by lauralisa** [comment]
Thank you!! I hope you can answer just one more question..
I can't get the panel to fix (to scroll separatly from the main container). Any tips?
Regards, Laura

**Comment by ahmedrad** [comment]
hi @lauralisa it's difficult for me to understand without seeing the code, is there a website or a fiddle or a codepen snippet I can check this issue in?

**Comment by lauralisa** [comment]
Hi Ahmed,

 

The url is www.lauralisa.nl/ralf <http://www.lauralisa.nl/ralf> , user = rm, pass = 643

The problem is that on mobile devices the whole page scrolls. The panel needs to be fixed. There is a submenu when you click on projects (than the panel needs to scroll).

 

I really appreciate your mail, thank you.

 

Van: Ahmed Radwan [mailto:notifications@github.com] 
Verzonden: Monday, November 9, 2015 9:16 PM
Aan: ahmedrad/sliiide <sliiide@noreply.github.com>
CC: lauralisa <info@lauralisa.nl>
Onderwerp: Re: [sliiide] Toggle image by click or swipe (#5)

 

hi @lauralisa <https://github.com/lauralisa>  it's difficult for me to understand without seeing the code, is there a website or a fiddle or a codepen snippet I can check this issue in?

**Comment by ahmedrad** [comment]
Hey @lauralisa,

It seems like there's a problem with fixed position elements and CSS transform. I don't think I'll be able to resolve it soon so I'll re-open this issue. You could just disable scroll all together on the page when the menu is open which would avoid the problem. Hope this helps!

Cheers,

**Comment by lauralisa** [comment]
Hi Ahmed,

 

Ok thank you. I cannot disable scroll because the submenu is too long. But i’ll find another way.

 

Regards,

Laura

 

Van: Ahmed Radwan [mailto:notifications@github.com] 
Verzonden: Friday, November 13, 2015 11:16 AM
Aan: ahmedrad/sliiide <sliiide@noreply.github.com>
CC: lauralisa <info@lauralisa.nl>
Onderwerp: Re: [sliiide] Toggle image by click or swipe (#5)

 

Hey @lauralisa <https://github.com/lauralisa> ,

It seems like there's a problem with fixed position elements and CSS transform. I don't think I'll be able to resolve it soon so I'll re-open this issue. You could just disable scroll all together on the page when the menu is open which would avoid the problem. Hope this helps!

Cheers,

**Comment by ahmedrad** [comment]
Hi @lauralisa 

I added a fix for the issue that you originally mentioned. Now the menu should be fixed as you scroll on a mobile page when you're not using the no_scroll option. Please update the js file and let me know how it went. I'm gonna go ahead and close this issue but will re-open it if you run into any related problems.

**Comment by lauralisa** [comment]
Hi Ahmed,

Great! I¹m sorry I cannot test it anymore, I¹ve solved it another way
around.
If I will use it again I will let you know.

Have a nice day,
Laura

Van:  Ahmed Radwan <notifications@github.com>
Beantwoorden - Aan:  ahmedrad/sliiide
<reply+00ef28211adc5c13629db52771bfd204487a518b6c4174b092cf00000001127d0ecf9
2a169ce06df6f76@reply.github.com>
Datum:  maandag 7 december 2015 10:09
Aan:  ahmedrad/sliiide <sliiide@noreply.github.com>
CC:  Laura Nieuwenhuis <info@lauralisa.nl>
Onderwerp:  Re: [sliiide] Toggle image by click or swipe (#5)


Hi @lauralisa <https://github.com/lauralisa>

I added a fix for the issue that you originally mentioned. Now the menu
should be fixed as you scroll on a mobile page when you're not using the
no_scroll option. Please update the js file and let me know how it went. I'm
gonna go ahead and close this issue but will re-open it if you run into any
related problems.


Reply to this email directly or view it on GitHub
<https://github.com/ahmedrad/sliiide/issues/5#issuecomment-162454725> .
