### ISSUE TITLE
Windows Phone 8 / IE10

### ISSUE THREAD

**Issue by generatepress** [ahmedrad/sliiide#6]
I've been getting reports of the plugin not working on Windows phones which seem to be using IE10: https://en.wikipedia.org/wiki/Windows_Phone_8#Web

Anyone else experiencing this?

**Comment by ahmedrad** [comment]
I released version 1.1 and changed up the way elements are position and how everything slide. Could potentially work better on windows phone but I have no way of testing a windows phone as I don't know a single human being who has one. I know you closed the issue but let me know if you're still running into any trouble @generatepress

**Comment by generatepress** [comment]
The issue was on my side - script is working great on a Windows phone (I had to use one at a Walmart to test haha).
