### ISSUE TITLE
overflow: scroll; not effecting the menu

### ISSUE THREAD

**Issue by phreak** [ahmedrad/sliiide#7]
Sorry, Issue can be deleted. Solved it and is not worth it to confuse other people. :)

**Comment by phreak** [comment]
Ok found it, for those having the same issue:

Change.
```function n(t){t=t||window.event,t.preventDefault&&t.preventDefault(),t.returnValue=!1}```

To
```function n(t){t=t||window.event,t.preventDefault&&t.preventDefault(),t.returnValue=!0}```

**Comment by ahmedrad** [comment]
no problem :) @phreak
