### ISSUE TITLE
effect where the menu appears on the website ?

### ISSUE THREAD

**Issue by vinylroads** [ahmedrad/sliiide#8]
Hi ! I like your plugin. Very nice. Is it possible to have an effect where the menu appears on the website without pushing it ?

**Comment by ahmedrad** [comment]
Hi @vinylroads,

I'm not really sure what you mean. You have all the flexibility when it comes to activating the menu. The returned object from calling the sliiide plugin has a few built in functions. You can use activate() and deactivate() whenever you need to show and hide the menu. So you can add you're own event listeners for whatever action you'd like the menu to appear on and call the needed method accordingly "either activate() or deactivate()". Hope this answers your question, if not feel free to provide any examples so I can better understand your question.

Cheers,
